minimumLimaVersion: 1.1.0

base:
- template://_images/ubuntu-lts
- template://_default/mounts

containerd:
  system: false
  user: false

provision:
- mode: data
  path: /etc/profile.d/99-linuxbrew.sh
  content: |
    ulimit -n 65536
    [ -e /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    command -v gcc >/dev/null 2>&1 && exit 0
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y build-essential
- mode: system
  script: |
    #!/bin/bash
    apt-get update
    apt-get upgrade -y
    apt-get install -y nala
- mode: user
  script: |
    #!/bin/bash
    set -eux -o pipefail
    [ -e /home/linuxbrew ] && exit 0
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
